### ISSUE TITLE
[Question] Orphaned network resources in GCE

### ISSUE THREAD

**Issue by Demonsthere** [istio/test-infra#1130] opened 2018-12-17 08:24 UTC
Hello,
We in [kyma](https://github.com/kyma-project) are using istio as a part of our stack, and found out that with prow we often have the problem, that some network resources (LoadBalancer objects in general) are not removed when istio is not properly deinstalled beforehand. 
As you are using prow, have you encountered a similar issue? 
How/Do you handle cleanup in the case that a cluster creation task is killed by prow before it can finish and cleanup? 

Best regards

**Comment by clarketm** [comment] 2019-09-15 03:28
It looks like the problem is resolved by: kyma-project/test-infra#275. If not please reopen.

**Closed as completed by clarketm** 2019-09-15 03:28 UTC
